CREATE DATABASE IF NOT EXISTS playtonight CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE playtonight;

CREATE TABLE IF NOT EXISTS games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    app_id INT UNIQUE NOT NULL,
    name VARCHAR(255),
    tags TEXT,
    genres TEXT,
    playtime_forever INT DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);